--------------------------------------------------------
--  File created - Tuesday-November-14-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PERSON
--------------------------------------------------------

  CREATE TABLE "KADI0000"."PERSON" 
   (	"SSN" NUMBER(*,0), 
	"PERSON_NAME" VARCHAR2(40 BYTE), 
	"BIRTHDATE" DATE, 
	"RACE" VARCHAR2(40 BYTE), 
	"GENDER" VARCHAR2(20 BYTE), 
	"PROFESSION" VARCHAR2(20 BYTE), 
	"MAILING_ADDRESS" VARCHAR2(100 BYTE), 
	"EMAIL" VARCHAR2(30 BYTE), 
	"HOME_NUMBER" NUMBER, 
	"WORK_NUMBER" NUMBER, 
	"PHONE_NUMBER" NUMBER, 
	"SUBSCRIPTION" VARCHAR2(5 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "KADI0000" ;
REM INSERTING into KADI0000.PERSON
SET DEFINE OFF;
Insert into KADI0000.PERSON (SSN,PERSON_NAME,BIRTHDATE,RACE,GENDER,PROFESSION,MAILING_ADDRESS,EMAIL,HOME_NUMBER,WORK_NUMBER,PHONE_NUMBER,SUBSCRIPTION) values (2,'Person2',to_date('01-JAN-90','DD-MON-RR'),'Asian','Female','Teacher','Address2','person2@gmail.com',456,789,123,'Yes');
Insert into KADI0000.PERSON (SSN,PERSON_NAME,BIRTHDATE,RACE,GENDER,PROFESSION,MAILING_ADDRESS,EMAIL,HOME_NUMBER,WORK_NUMBER,PHONE_NUMBER,SUBSCRIPTION) values (3,'Person3',to_date('08-MAY-92','DD-MON-RR'),'Middle East','Male','Analyst','Address3','person3@gmail.com',333,333,333,'No');
Insert into KADI0000.PERSON (SSN,PERSON_NAME,BIRTHDATE,RACE,GENDER,PROFESSION,MAILING_ADDRESS,EMAIL,HOME_NUMBER,WORK_NUMBER,PHONE_NUMBER,SUBSCRIPTION) values (1,'Person1',to_date('16-FEB-96','DD-MON-RR'),'American','Male','Professor','Address1','person1@gmail.com',123,456,789,'Yes');
Insert into KADI0000.PERSON (SSN,PERSON_NAME,BIRTHDATE,RACE,GENDER,PROFESSION,MAILING_ADDRESS,EMAIL,HOME_NUMBER,WORK_NUMBER,PHONE_NUMBER,SUBSCRIPTION) values (4,'Person4',to_date('15-SEP-95','DD-MON-RR'),'Europe','Male','Plumber','Address4','person4@gmail.com',444,444,444,'Yes');
Insert into KADI0000.PERSON (SSN,PERSON_NAME,BIRTHDATE,RACE,GENDER,PROFESSION,MAILING_ADDRESS,EMAIL,HOME_NUMBER,WORK_NUMBER,PHONE_NUMBER,SUBSCRIPTION) values (5,'Person5',to_date('21-NOV-91','DD-MON-RR'),'Africa','Female','Astronaut','Address5','person5@gmail.com',555,555,555,'No');
--------------------------------------------------------
--  DDL for Index SYS_C00188349
--------------------------------------------------------

  CREATE UNIQUE INDEX "KADI0000"."SYS_C00188349" ON "KADI0000"."PERSON" ("SSN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "KADI0000" ;
--------------------------------------------------------
--  Constraints for Table PERSON
--------------------------------------------------------

  ALTER TABLE "KADI0000"."PERSON" ADD PRIMARY KEY ("SSN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "KADI0000"  ENABLE;
